create table if not exists public.vibes (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('note', 'drawing')),
  content text not null check (char_length(content) between 1 and 2000),
  name text not null default 'Anonyme' check (char_length(name) between 1 and 50),
  color text not null default '#ffffff' check (color ~ '^#[0-9A-Fa-f]{6}$'),
  rotation real not null default 0 check (rotation between -6 and 6),
  created_at timestamptz not null default now()
);

alter table public.vibes enable row level security;

grant select, insert on table public.vibes to anon, authenticated;
grant usage, select on sequence public.vibes_id_seq to anon, authenticated;

create policy "Public vibes are readable"
on public.vibes for select
to anon, authenticated
using (true);

create policy "Visitors can publish vibes"
on public.vibes for insert
to anon, authenticated
with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('vibe-drawings', 'vibe-drawings', true, 2097152, array['image/webp', 'image/png'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Vibe drawings are public"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'vibe-drawings');

create policy "Visitors can upload vibe drawings"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'vibe-drawings');

alter publication supabase_realtime add table public.vibes;
